"""add tax_rate and is_classified to invoices

Revision ID: 2eea1d1a42ba
Revises: a1b2c3d4e5f6
Create Date: 2026-03-31 01:47:11.139298

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2eea1d1a42ba"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices", sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column("invoices", sa.Column("is_classified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_invoices_is_classified"), "invoices", ["is_classified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_is_classified"), table_name="invoices")
    op.drop_column("invoices", "is_classified")
    op.drop_column("invoices", "tax_rate")
    # ### end Alembic commands ###
