"""add_company_user_relationship

Revision ID: 3bdf71e9b27a
Revises: f86530512cfd
Create Date: 2026-04-02 14:14:22.847147

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bdf71e9b27a"
down_revision: Union[str, Sequence[str], None] = "f86530512cfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("user_id", sa.BIGINT(), nullable=False))
    op.alter_column("companies", "ksef_token", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "companies", ["user_id"])
    op.create_foreign_key(None, "companies", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.drop_constraint(None, "companies", type_="unique")
    op.alter_column("companies", "ksef_token", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("companies", "user_id")
    # ### end Alembic commands ###
