"""add bank_transactions table

Revision ID: 687a4ef8432a
Revises: 2eea1d1a42ba
Create Date: 2026-03-31 18:04:24.612117

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "687a4ef8432a"
down_revision: Union[str, Sequence[str], None] = "2eea1d1a42ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.BIGINT(), sa.Identity(always=True), nullable=False),
        sa.Column("company_id", sa.BIGINT(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payee", sa.String(), nullable=True),
        sa.Column("memo", sa.String(), nullable=True),
        sa.Column("transaction_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bank_transactions_company_id"), "bank_transactions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_bank_transactions_transaction_hash"),
        "bank_transactions",
        ["transaction_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bank_transactions_transaction_hash"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_company_id"), table_name="bank_transactions")
    op.drop_table("bank_transactions")
    # ### end Alembic commands ###
