"""init db models

Revision ID: c394c8591868
Revises:
Create Date: 2026-03-27 20:17:50.020225

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c394c8591868"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.BIGINT(), sa.Identity(always=True), nullable=False),
        sa.Column("nip", sa.String(length=10), nullable=False),
        sa.Column("ksef_token", sa.String(), nullable=False),
        sa.Column("last_sync_hwm_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_nip"), "companies", ["nip"], unique=True)
    op.create_table(
        "invoices",
        sa.Column("id", sa.BIGINT(), sa.Identity(always=True), nullable=False),
        sa.Column("company_id", sa.BIGINT(), nullable=False),
        sa.Column("ksef_reference_number", sa.String(), nullable=False),
        sa.Column("invoice_number", sa.String(), nullable=True),
        sa.Column("issue_date", sa.DateTime(), nullable=True),
        sa.Column("seller_nip", sa.String(length=10), nullable=True),
        sa.Column("total_gross", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("xml_file_path", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING_DOWNLOAD", "DOWNLOADED", "PARSED", "ERROR", name="invoicestatus"),
            nullable=False,
        ),
        sa.Column("parsed_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_company_id"), "invoices", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_ksef_reference_number"),
        "invoices",
        ["ksef_reference_number"],
        unique=True,
    )
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "ksef_sessions",
        sa.Column("id", sa.BIGINT(), sa.Identity(always=True), nullable=False),
        sa.Column("company_id", sa.BIGINT(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ksef_sessions")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_ksef_reference_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_company_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_companies_nip"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
